<img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRadYXBHB9wMOqYz9V7AbbUGs-DNh6R7pTcdaa-1u2R2w&s=10" width="300">

## What is Pandas?

Pandas is an open-source Python library for storing, cleaning, analyzing and manipulating tabular data. Main structures: Series and DataFrame.

## History

First released in 2008 by Wes McKinney to simplify fast data analysis in Python.

## Why Pandas?

It makes reading CSV/Excel files, cleaning data, filtering, grouping and analysis easy.

## Features

- Fast
- Data cleaning
- File support
- Grouping
- Statistics
- Works with NumPy

<img src="https://media.geeksforgeeks.org/wp-content/uploads/20251205172335757797/pandas_basic_operations.webp" width="500">

## Applications

Data Science, AI, ML, Finance, Healthcare, Business Analytics

Install pandas if needed.

In [ ]:
# Install Pandas
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Import pandas and check version.

In [ ]:
import pandas as pd
print(pd.__version__)

2.2.2

Create a Series.

In [ ]:
s=pd.Series([10,20,30,40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64

Create a DataFrame.

In [ ]:
data={'Name':['Rahul','Priya','Amit'],'Age':[20,19,21],'Marks':[88,91,75]}
df=pd.DataFrame(data)
df

    Name  Age  Marks
0  Rahul   20     88
1  Priya   19     91
2   Amit   21     75

Display first rows.

In [ ]:
df.head()

    Name  Age  Marks
0  Rahul   20     88
1  Priya   19     91
2   Amit   21     75

Display last rows.

In [ ]:
df.tail()

    Name  Age  Marks
0  Rahul   20     88
1  Priya   19     91
2   Amit   21     75

Dataset information.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

Statistical summary.

In [ ]:
df.describe()

        Age      Marks
count   3.0   3.000000
mean   20.0  84.666667
std     1.0   8.504901
min    19.0  75.000000
25%    19.5  81.500000
50%    20.0  88.000000
75%    20.5  89.500000
max    21.0  91.000000

Add a new column.

In [ ]:
df['Grade']=['A','A+','B']
df

    Name  Age  Marks Grade
0  Rahul   20     88     A
1  Priya   19     91    A+
2   Amit   21     75     B

Filter rows.

In [ ]:
df[df['Marks']>80]

    Name  Age  Marks Grade
0  Rahul   20     88     A
1  Priya   19     91    A+

Sort data.

In [ ]:
df.sort_values('Marks')

    Name  Age  Marks Grade
2   Amit   21     75     B
0  Rahul   20     88     A
1  Priya   19     91    A+

Count missing values.

In [ ]:
df.isnull().sum()

Name     0
Age      0
Marks    0
Grade    0
dtype: int64

Mean marks.

In [ ]:
df['Marks'].mean()

np.float64(84.66666666666667)

Delete Column

In [ ]:
df.drop("Age",axis=1,inplace=True)

print(df)

    Name  Marks Grade
0  Rahul     88     A
1  Priya     91    A+
2   Amit     75     B

Rename Column

In [ ]:
df.rename(columns={"Marks":"Score"},inplace=True)

print(df)

    Name  Score Grade
0  Rahul     88     A
1  Priya     91    A+
2   Amit     75     B

Maximum

In [ ]:
df["Score"].max()

91

Minimum

In [ ]:
df["Score"].min()

75

Merge DataFrames

In [ ]:
df1 = pd.DataFrame({
    "ID":[1,2],
    "Name":["Rahul","Priya"]
})

df2 = pd.DataFrame({
    "ID":[1,2],
    "Marks":[90,95]
})

result = pd.merge(df1,df2,on="ID")

print(result)

   ID   Name  Marks
0   1  Rahul     90
1   2  Priya     95

# **Useful Functions**

pd.Series()

pd.DataFrame()

pd.read_csv()

pd.read_excel()

pd.to_csv()

pd.to_excel()

head()

tail()

info()

describe()

shape

columns

dtypes

loc

iloc

drop()

rename()

sort_values()

groupby()

value_counts()

unique()

nunique()

isnull()

fillna()

dropna()

merge()

concat()

mean()

median()

max()

min()

sum()

count()

## Summary
Pandas is an essential library for data analysis and is widely used in Data Science and Machine Learning.